# Generated by Django 6.0.3 on 2026-07-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(default='active', max_length=255),
            preserve_default=False,
        ),
    ]
