# Generated by Django 6.0.3 on 2026-07-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='Products_info',
            field=models.CharField(default='product', max_length=255),
            preserve_default=False,
        ),
    ]
