# Generated by Django 6.0.3 on 2026-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_evidence/'),
        ),
    ]
